library(readxl)
library(timevis)
library(dplyr)
library(here)
dat <- read_xlsx("data/timeline.xlsx")
dat$start <- as.character(dat$start)
dat$end <- as.character(dat$end)
dat$id <- 1:nrow(dat)
dat$content <- paste(dat$content, "-", dat$notes)
groups <- tibble(content=unique(dat$group), id=content)
groups$bgcolour <- c("#8c510a", "#d8b365", "#f6e8c3", "#f5f5f5", "#c7eae5", "#5ab4ac", "#01665e")
groups$colour <- c("white", "black", "black", "black", "black", "black", "white")
groups$style <- paste0("color: ", groups$colour, "; background-color: ", groups$bgcolour, ";")
dat <- inner_join(dat, subset(groups, select=c(id, style)), by=c("group"="id"))
groups <- subset(groups, select=c(id, content))
timevis(dat, groups, width=1960)
