---
output: vitae::awesomecv
csl: "../resources/nature.csl"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(vitae)
library(bib2df)
library(here)
library(glue)

separate_why <- function(x)
{
  x %>%
    dplyr::mutate(why = strsplit(why, "\\. ")) %>%
    tidyr::unnest(why)
}
```


```{r}
load(here("data", "pubs.rdata"))

pubs <- pubs %>% 
  filter(year >= 2018)

temp <- list(
  pubid="temp",
  title="The importance of family based sampling for biobanks",
  author="NM Davies, G Hemani, JM Neiderhiser, HC Martin, MC Mills, PM Visscher, L Yengo, AS Young, MC Keller",
  journal="Nature",
  number="In press",
  cites=0,
  year=2024,
  cid=NA
) %>% as.data.frame()

# pubs <- bind_rows(temp, pubs)

convert_to_bib <- function(x)
{
  Encoding(x$author) <- "UTF-8"
  x$author <- iconv(x$author, "UTF-8", "UTF-8", sub="")
  x$pubid <- gsub("-", "", x$pubid)
  x$author <- sapply(x$author, function(string)
  {
    authors = trimws(unlist(strsplit(string, ",")))
    format_author = function(author) {
        words = trimws(unlist(strsplit(author, " ")))
        lastname = words[length(words)]
        first = words[!words %in% lastname]
        first = gsub("\\B[a-z]", "", first, perl = TRUE)
        first = paste(first, collapse = "")
        trimws(paste(first, lastname))
    }
    authors = sapply(authors, format_author)
    paste(authors, collapse = ", ")
  })

  tmpfile <- here("data", "pubs.bib")
  tibble(
    CATEGORY="ARTICLE",
    BIBTEXKEY=x$pubid,
    AUTHOR=
      strsplit(x$author, split=", ") %>%
      lapply(., function(i) {
        stringr::str_split(i, " ", n=2) %>%
        sapply(., function(j) {
          paste(rev(j), collapse=", ")
          }) %>%
        gsub("al, e", "others", .)
      }),
    TITLE=x$title,
    JOURNAL=x$journal,
    NUMBER=x$number,
    YEAR=x$year
  ) %>% bib2df::df2bib(file=tmpfile)
  bibliography_entries(tmpfile)
}
```

# Publications

```{r}
pubs %>% 
  convert_to_bib()
```
